/**
 * DeepCode Harness — Agent 免疫系统
 *
 * 模块六：执行后独立审查 + 违规 Skill 固化
 *
 * ============================================================
 * 设计背景
 * ============================================================
 *
 * 论文 I-01（Agent 免疫系统）核心洞察：
 * LLM Agent 在长任务中容易"遗忘"初始约束（如"修改前先备份"）。
 * 原因：注意力稀释 + 多步推理累积误差。
 *
 * 解决方案：
 * 1. Checkpoint 处触发独立审查（不是每步，避免过度干扰）
 * 2. 审查输入：硬约束列表 + 产出物（不读执行日志，避免上下文膨胀）
 * 3. 发现违规 → 固化为可执行 Skill → 外挂到后续执行流
 *
 * 这形成负反馈闭环：犯错 → 检测 → 产生抗体（Skill）→ 下次自动规避。
 * 与模块七的 propose_skill 正向闭环互补（正：总结好模式；负：修复违规）。
 *
 * ============================================================
 * 审查粒度设计
 * ============================================================
 *
 * 为什么不在每个 tool use 后审查？
 * - 延迟过大（每次审查都是一次 LLM 调用）
 * - 打断执行流，降低连贯性
 * - Checkpoint 是自然的停顿点（PlanStep 完成、用户消息间隔、写入操作后）
 *
 * 为什么不读执行日志？
 * - 日志包含大量无关内容，浪费 token
 * - 只看产出物（修改了什么文件）+ 约束列表，审查更精准
 * - 符合论文"约束 → 产出物"的直接映射原则
 *
 * @module
 */

import { Context, Effect, Layer, Ref } from "effect"
import { makeLocationNode } from "../../effect/app-node"
import type { HardConstraint } from "../hard-constraint/extractor"

// ============================================================
// 类型定义
// ============================================================

/**
 * 违规记录
 *
 * @property violationDescription - 违规描述（人类可读）
 * @property evidence             - 证据（哪些文件/操作违反了哪条约束）
 * @property severity             - 严重程度（low/medium/high）
 */
export interface Violation {
  constraintId: string
  constraintText: string
  violationDescription: string
  evidence: string
  severity: "low" | "medium" | "high"
}

/**
 * 一次审查结果
 *
 * @property passed - 是否通过（无违规）
 */
export interface ReviewResult {
  checkpointId: string
  timestamp: number
  violations: Violation[]
  suggestedSkills: ImmuneSkill[]
  passed: boolean
}

/**
 * 免疫 Skill（自动生成的纠正技能）
 *
 * 固化格式兼容 SuperPowers Skill 系统：
 * - name: 唯一标识（immune- 前缀）
 * - trigger: 触发条件（如"before write/edit"）
 * - check: 检查逻辑（自然语言描述，后续编译为可执行代码）
 * - action: 违规时的自动修复动作
 */
export interface ImmuneSkill {
  name: string
  description: string
  trigger: string
  check: string
  action: string
  autoGenerated: true
}

// ============================================================
// 服务接口
// ============================================================

export interface Interface {
  /**
   * 在 Checkpoint 处执行审查
   *
   * @param checkpointId - Checkpoint 标识（如 "step-3"、"plan-complete"）
   * @param constraints  - 当前活跃硬约束列表
   * @param artifacts    - 本轮产出物描述（如 "Modified: src/payment.ts"）
   * @returns 审查结果（含违规列表和建议 Skill）
   */
  readonly reviewCheckpoint: (
    checkpointId: string,
    constraints: HardConstraint[],
    artifacts: string[],
  ) => Effect.Effect<ReviewResult>

  /** 获取历史审查记录 */
  readonly getReviewHistory: () => Effect.Effect<ReviewResult[]>

  /** 获取所有自动生成的免疫 Skill */
  readonly getImmuneSkills: () => Effect.Effect<ImmuneSkill[]>
}

/** DI token */
export class Service extends Context.Service<Service, Interface>()(
  "@opencode/v2/DeepCodeImmuneSystem",
) {}

// ============================================================
// 纯函数逻辑
// ============================================================

/**
 * 从约束文本生成免疫 Skill 名称
 */
function generateSkillName(constraint: HardConstraint): string {
  const base = constraint.pattern
    .replace(/[^a-zA-Z0-9\u4e00-\u9fa5]/g, "-")
    .slice(0, 30)
  return `immune-${base}`
}

/**
 * 从违规生成纠正 Skill
 *
 * 根据违规类型生成对应的防范措施：
 * - 备份类违规 → 自动备份动作
 * - 删除类违规 → 确认删除动作
 * - 其他 → 通用合规检查
 */
function synthesizeSkill(constraint: HardConstraint, violation: Violation): ImmuneSkill {
  // 根据违规描述推断动作
  let action = `Ensure compliance with: ${constraint.pattern}`
  if (violation.violationDescription.toLowerCase().includes("backup")) {
    action = "First create a backup (.bak) of the target file before modifying"
  } else if (violation.violationDescription.toLowerCase().includes("delet")) {
    action = "Check if the target should be preserved before deletion"
  }

  return {
    name: generateSkillName(constraint),
    description: `Auto-generated immune skill for constraint: ${constraint.pattern}`,
    trigger: "Before write/edit operations matching the constraint scope",
    check: `Verify that the operation complies with: ${constraint.pattern}`,
    action,
    autoGenerated: true,
  }
}

// ============================================================
// Layer 实现
// ============================================================

const layer = Layer.effect(
  Service,
  Effect.gen(function* () {
    // 两个 Ref 维护审查状态
    const history = yield* Ref.make<ReviewResult[]>([])
    const skills = yield* Ref.make<ImmuneSkill[]>([])

    return Service.of({
      /**
       * reviewCheckpoint：执行 Checkpoint 审查
       *
       * 第一阶段实现（当前）：基于规则的简单检查
       * - 查找"必须备份"类型约束
       * - 检查 artifacts 中是否有备份迹象（.bak、.backup 关键词）
       * - 无备份 + 有修改 → 违规
       *
       * 第二阶段（TD-001）：接入 Pro 模型做语义审查
       * - 构造审查 prompt，传入约束和产出物
       * - 让 Pro 模型逐条检查约束是否遵守
       * - 解析返回的违规列表
       */
      reviewCheckpoint: Effect.fn("DeepCodeImmuneSystem.reviewCheckpoint")(
        (checkpointId: string, constraints: HardConstraint[], artifacts: string[]) =>
          Effect.gen(function* () {
            const violations: Violation[] = []
            const newSkills: ImmuneSkill[] = []

            // TODO(阶段三): 调用 Pro 模型做独立 LLM 审查
            // 当前：基于规则的备份约束检查
            for (const c of constraints) {
              // 查找"备份"类必须约束
              if (c.type === "require" && /备份|backup/.test(c.pattern)) {
                // 检查 artifacts 中是否有备份文件
                const hasBackup = artifacts.some(
                  (a) => a.includes(".bak") || a.includes(".backup") || a.includes("备份"),
                )
                // 检查是否有写入操作
                const hasWrite = artifacts.some(
                  (a) =>
                    a.toLowerCase().includes("write") ||
                    a.toLowerCase().includes("edit") ||
                    a.toLowerCase().includes("modified"),
                )
                // 有写入但无备份 → 违规
                if (!hasBackup && hasWrite) {
                  const violation: Violation = {
                    constraintId: c.id,
                    constraintText: c.pattern,
                    violationDescription: "Modified files without creating backup first",
                    evidence: artifacts.join(", "),
                    severity: "medium",
                  }
                  violations.push(violation)
                  newSkills.push(synthesizeSkill(c, violation))
                }
              }
            }

            const result: ReviewResult = {
              checkpointId,
              timestamp: Date.now(),
              violations,
              suggestedSkills: newSkills,
              passed: violations.length === 0,
            }

            // 记录审查历史
            yield* Ref.update(history, (h) => [...h, result])
            // 添加新 Skill
            if (newSkills.length > 0) {
              yield* Ref.update(skills, (s) => [...s, ...newSkills])
            }

            return result
          }),
      ),

      getReviewHistory: () => Ref.get(history),
      getImmuneSkills: () => Ref.get(skills),
    })
  }),
)

/** LocationNode 导出 */
export const node = makeLocationNode({
  name: "deepcode-immune-system",
  layer,
  deps: [],
})
